{{- if .Values.ingress.enabled -}}
{{- $fullName := include "core.fullname" . -}}
{{- $flowerEnabled := .Values.flower.enabled -}}
{{- $flowerPort := .Values.flower.service.port -}}
{{- $backendPort := .Values.backend.service.port -}}
{{- $hosts := .Values.ingress.hosts | default (list .Values.ingress.host) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "core.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- if $flowerEnabled }}
        - path: /flower/
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-celery-flower
              port:
                number: {{ $flowerPort }}
        {{- end }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-backend
              port:
                number: {{ $backendPort }}
    {{- end }}
{{- end }}
