apiVersion: v2
name: core
description: A Helm chart for Kubernetes
type: application
version: 0.6.0
appVersion: "core-2.10.1"

dependencies:
  - name: postgresql
    version: "14.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 18.19.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: elasticsearch
    version: 21.4.8
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: elasticsearch.enabled
  - name: keyvault
    version: 0.1.3
    repository: file://../keyvault
    condition: keyvault.enabled
