apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reporting.fullname" . }}-release
  labels:
    {{- include "reporting.labels" . | nindent 4 }}
    reporting/job: upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "reporting.labels" . | nindent 8 }}
        reporting/job: upgrade
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend-release
          command: ["/bin/sh"]
          args: ["-c", "python3 /code/manage.py upgrade"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          {{ include "keyvault.secretRef" . | nindent 12 }}
            - configMapRef:
                name: {{ include "reporting.fullname" . }}-backend
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ include "keyvault.volumeMounts" . | nindent 12 }}
      restartPolicy: Never
      volumes:
        {{ include "keyvault.volumes" . | nindent 8 }}
  backoffLimit: 3