apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-gateway.fullname" . }}-backend
  labels:
    {{- include "payment-gateway.labels" . | nindent 4 }}
data:
  WESTERN_UNION_CERT: "/certs/tls.crt"
  WESTERN_UNION_KEY: "/certs/tls.key"
{{- range $key, $value :=  .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
