apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-gateway.fullname" . }}-backend
  labels:
    {{- include "payment-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "payment-gateway.selectorLabels" . | nindent 6 }}
      service: "backend"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "payment-gateway.selectorLabels" . | nindent 8 }}
        service: "backend"
    spec:
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ include "payment-gateway.serviceAccountName" . }}
      initContainers:
        {{- if .Values.keyvault.enabled }}
        {{ include "payment-gateway.decodeCerts" . | nindent 8 }}
        {{- end }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{ include "keyvault.secretRef" . | nindent 12 }}
            - configMapRef:
                name: {{ include "payment-gateway.fullname" . }}-backend
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ include "keyvault.volumeMounts" . | nindent 12 }}
            {{- if .Values.keyvault.enabled }}
            {{ include "payment-gateway.tlsVolumeMounts" . | nindent 12 }}
            {{- end }}
      volumes:
        {{ include "keyvault.volumes" . | nindent 8 }}
        {{- if .Values.keyvault.enabled }}
        {{ include "payment-gateway.tlsVolumes" . | nindent 8 }}
        {{- end }}
