apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-gateway.fullname" . }}-backend
  labels:
    {{- include "payment-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    {{- include "payment-gateway.selectorLabels" . | nindent 4 }}
    service: "backend"
