apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.fullname" . }}-backend
  labels:
    {{- include "core.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value :=  .Values.backend.secret }}
{{- if eq "bool" (typeOf $value) }}
{{- $stringValue := $value | toString }}
  {{ $key }}: {{ $stringValue | b64enc | quote }}
{{- else }}
  {{- if eq $value "" }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf 
      "postgis://%s:%s@%s:%d/%s"
      .Values.postgresql.auth.username
      .Values.postgresql.auth.password
      (printf "%s-postgresql" .Release.Name)
      5432
      "hopedb" | b64enc | quote
  }}
{{- end }}
{{- if .Values.redis.enabled }}
  CELERY_BROKER_URL: {{ printf 
      "redis://%s-redis-master:6379/0"
      .Release.Name | b64enc | quote
  }}
  CELERY_RESULT_BACKEND: {{ printf 
      "redis://%s-redis-master:6379/1"
      .Release.Name | b64enc | quote
  }}
  CACHE_LOCATION: {{ printf 
      "redis://%s-redis-master:6379/2"
      .Release.Name | b64enc | quote
  }}
  CONSTANCE_REDIS_CONNECTION: {{ printf 
      "redis://%s-redis-master:6379/3"
      .Release.Name | b64enc | quote
  }}
{{- end }}
{{- if .Values.elasticsearch.enabled }}
  ELASTICSEARCH_HOST: {{ printf
      "http://%s-elasticsearch:9200"
      .Release.Name | b64enc | quote
  }}
{{- end }}