apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.fullname" . }}-backend
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      {{- if .Values.nginx.enabled }}
      port: {{ .Values.nginx.service.port }}
      {{- else }}
      port: {{ .Values.backend.service.port }}
      {{- end }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "core.selectorLabels" . | nindent 4 }}
    core/service: backend
