global:
  imagePullSecrets: []

backend:
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8000

  autoscaling:
    enabled: false

celery:
  autoscaling:
    enabled: false

image:
  repository: unicef/hope-payment-gateway
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

keyvault:
  enabled: true
  envMappings: []
  mountPath: /mnt/secrets
  secretName: "keyvault-secret"

rollme:
  enabled: false

serviceAccount:
  create: false

flower:
  enabled: false
  service:
    port: 5555

ingress:
  enabled: true

redis:
  enabled: true