apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aurora.fullname" . }}-aurora
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
data:
{{- range $key, $value :=  .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
