apiVersion: v1
kind: Service
metadata:
  name: {{ include "reporting.fullname" . }}
  labels:
    {{- include "reporting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reporting.selectorLabels" . | nindent 4 }}
