apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deduplication-engine.fullname" . }}-model-downloader
  labels:
    {{- include "deduplication-engine.labels" . | nindent 4 }}
    deduplication-engine/job: model-downloader
  annotations:
    "helm.sh/hook": pre-upgrade, post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "deduplication-engine.labels" . | nindent 8 }}
        deduplication-engine/job: model-downloader
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend-model-downloader
          args: ["download_model"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          {{ include "keyvault.secretRef" . | nindent 12 }}
            - configMapRef:
                name: {{ include "deduplication-engine.fullname" . }}-backend
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ include "keyvault.volumeMounts" . | nindent 12 }}
      restartPolicy: Never
      volumes:
        {{ include "keyvault.volumes" . | nindent 8 }}
  backoffLimit: 3