{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "deduplication-engine.fullname" . }}-ingress
  labels:
    {{- include "deduplication-engine.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- if .Values.flower.enabled }}
        - path: /flower/
          pathType: Prefix
          backend:
            service:
              name: {{ include "deduplication-engine.fullname" . }}-celery-flower
              port:
                number: {{ .Values.flower.service.port }}
        {{- end }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "deduplication-engine.fullname" . }}-backend
              port:
                number: {{ .Values.backend.service.port }}
{{- end }}
