{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
  labels:
    {{- include "deduplication-engine.labels" . | nindent 4 }}
data:
  redis.conf: |
    port 6379
    dir /data
    appendonly yes
    protected-mode no
    databases 32
{{- end }}
