apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workspace.fullname" . }}-backend
  labels:
    {{- include "workspace.labels" . | nindent 4 }}
data:
{{- range $key, $value :=  .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
