apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deduplication-engine.fullname" . }}-model-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile