{{- if .Values.flower.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}-flower
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
{{- range $key, $value :=  .Values.flower.config }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}-flower-entrypoint
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/flower/entrypoint.sh").AsConfig | indent 2}}
{{- end }}