{{- if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}-celery-flower
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      {{- include "core.selectorLabels" . | nindent 6 }}
      core/service: celery-flower
  template:
    metadata:
      annotations:
    {{- if .Values.flower.podAnnotations }}
        {{- toYaml .Values.flower.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "core.selectorLabels" . | nindent 8 }}
        core/service: celery-flower
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "core.serviceAccountName" . }}
      volumes:
      - configMap:
          defaultMode: 511
          name: {{ include "core.fullname" . }}-flower-entrypoint
        name: entrypoint
      containers:
        - name: {{ .Chart.Name }}-celery-flower
          securityContext:
            {{- toYaml .Values.flower.securityContext | nindent 12 }}
          image: "{{ .Values.flower.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.flower.service.port }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ include "core.fullname" . }}-flower
          - configMapRef:
              name: {{ include "core.fullname" . }}-flower
          volumeMounts:
          - name: entrypoint
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
          readinessProbe:
            httpGet:
              path: /_health
              port: {{ .Values.flower.service.port }}
              httpHeaders:
              - name: X-Health
                value:  "Kubernetes-Health"
              - name: Host
                value: "kubernetes.internal"
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}