{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.fullname" . }}-flower
  labels:
    {{- include "core.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.redis.enabled }}
  FLOWER_BROKER_API: {{ printf
      "http://%s-redis-master:8000"
      .Release.Name | b64enc | quote
  }}
  FLOWER_BROKER: {{ printf
      "redis://%s-redis-master:6379/0"
      .Release.Name | b64enc | quote
  }}
  CELERY_BROKER_URL: {{ printf
      "redis://%s-redis-master:6379/0"
      .Release.Name | b64enc | quote
  }}
{{- end }}
{{- range $key, $value :=  .Values.flower.secret }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}