apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status.fullname" . }}-status
  labels:
    {{- include "status.labels" . | nindent 4 }}
data:
{{- range $key, $value :=  .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}